<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Capítulo 14 Resumiendo y relacionado los datos | Aprendiendo R sin morir en el intento</title>
<meta name="author" content="Javier Álvarez Liébana">
<meta name="description" content="Ahora que ya sabemos depurar y transformar los datos con pocas líneas de código, así como extraer la información que nos interese, en esta sección vamos a aprender dos cosas básicas a la hora de...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Capítulo 14 Resumiendo y relacionado los datos | Aprendiendo R sin morir en el intento">
<meta property="og:type" content="book">
<meta property="og:image" content="/img/logo_R.png">
<meta property="og:description" content="Ahora que ya sabemos depurar y transformar los datos con pocas líneas de código, así como extraer la información que nos interese, en esta sección vamos a aprender dos cosas básicas a la hora de...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Capítulo 14 Resumiendo y relacionado los datos | Aprendiendo R sin morir en el intento">
<meta name="twitter:description" content="Ahora que ya sabemos depurar y transformar los datos con pocas líneas de código, así como extraer la información que nos interese, en esta sección vamos a aprender dos cosas básicas a la hora de...">
<meta name="twitter:image" content="/img/logo_R.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/_Sen-0.4.0/font.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=DM%20Mono&amp;display=swap" rel="stylesheet">
<link href="libs/_Bitter-0.4.0/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.3.0/transition.js"></script><script src="libs/bs3compat-0.3.0/tabs.js"></script><script src="libs/bs3compat-0.3.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="libs/datatables-binding-0.18/datatables.js"></script><link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script><link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Aprendiendo R sin morir en el intento</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Prefacio</a></li>
<li class="book-part">Toma de contacto</li>
<li><a class="" href="instalacionR.html"><span class="header-section-number">1</span> Instalación</a></li>
<li><a class="" href="primeros-pasos.html"><span class="header-section-number">2</span> Primeros pasos</a></li>
<li class="book-part">Conceptos básicos</li>
<li><a class="" href="vectores.html"><span class="header-section-number">3</span> Tipos de datos I: vectores</a></li>
<li><a class="" href="operacionesvectores.html"><span class="header-section-number">4</span> Operaciones con vectores</a></li>
<li><a class="" href="proyecto.html"><span class="header-section-number">5</span> Flujo de trabajo: primer proyecto</a></li>
<li><a class="" href="control.html"><span class="header-section-number">6</span> Estructuras de control</a></li>
<li><a class="" href="datos.html"><span class="header-section-number">7</span> Tipos de datos II: datos estructurados</a></li>
<li><a class="" href="importar-exportar.html"><span class="header-section-number">8</span> Importando/exportando</a></li>
<li class="book-part">Listas y funciones</li>
<li><a class="" href="otros-datos.html"><span class="header-section-number">9</span> Listas y factores</a></li>
<li><a class="" href="funciones.html"><span class="header-section-number">10</span> Creación de funciones</a></li>
<li class="book-part">Alto en el camino</li>
<li><a class="" href="resumen-1.html"><span class="header-section-number">11</span> ¿Qué sabemos hacer?</a></li>
<li class="book-part">EXPLORANDO: introducción al análisis exploratorio de datos</li>
<li><a class="" href="tidydata.html"><span class="header-section-number">12</span> Tidy data: ordenando datos</a></li>
<li><a class="" href="tidyverse.html"><span class="header-section-number">13</span> Explorando los datos: incursión a tidyverse</a></li>
<li><a class="active" href="resumenes.html"><span class="header-section-number">14</span> Resumiendo y relacionado los datos</a></li>
<li><a class="" href="ggplot2.html"><span class="header-section-number">15</span> Visualizando datos: incursión a ggplot2</a></li>
<li class="book-part">Epílogo</li>
<li><a class="" href="contribuye.html"><span class="header-section-number">16</span> Contribuye al proyecto</a></li>
<li><a class="" href="bibliograf%C3%ADa.html">Bibliografía</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/dadosdelaplace/intro-R">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="resumenes" class="section level1">
<h1>
<span class="header-section-number">Capítulo 14</span> Resumiendo y relacionado los datos<a class="anchor" aria-label="anchor" href="#resumenes"><i class="fas fa-link"></i></a>
</h1>
<p>Ahora que <strong>ya sabemos depurar y transformar los datos</strong> con pocas líneas de código, así como extraer la información que nos interese, en esta sección vamos a aprender dos cosas básicas a la hora de trabajar con datos:</p>
<ul>
<li>Realizar <strong>resúmenes numéricos</strong> de los datos, de forma general pero también cuando queremos calcular estadísticas desagregadas por grupos.</li>
<li>
<strong>Relacionar tablas</strong> entre sí (los famosos <em>join</em>).</li>
</ul>
<div id="tablas-de-frecuencias" class="section level2">
<h2>
<span class="header-section-number">14.1</span> Tablas de frecuencias<a class="anchor" aria-label="anchor" href="#tablas-de-frecuencias"><i class="fas fa-link"></i></a>
</h2>
<p>Una de las <strong>primeras cosas</strong> que uno aprende en la asignatura de estadística <strong>descriptiva</strong> es <strong>saber resumir nuestros datos</strong> cuando tenemos muchos, y además <strong>muchos valores repetidos</strong>. Vamos a construir la <strong>tabla de frecuencias</strong> de la variable <code>n_films</code> de nuestro ya conocido conjunto <code>starwars</code> (una variable que vamos a crear contando en cuántas películas aparece cada personaje)</p>
<div class="sourceCode" id="cb958"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://purrr.tidyverse.org">purrr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="va">starwars_nueva</span> <span class="op">&lt;-</span> <span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>n_films <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/purrr/man/map.html">map_int</a></span><span class="op">(</span><span class="va">films</span>, <span class="va">length</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Y lo primero es <strong>contar</strong>: ¿cuántos registros hay de cada una de las clases? Para ello usaremos la función <code>count()</code></p>
<div class="sourceCode" id="cb959"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars_nueva</span> <span class="op">%&gt;%</span> <span class="fu">count</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##       n
##   &lt;int&gt;
## 1    87</code></pre>
<p>Como ves si aplicamos la <strong>función directamente</strong> simplemente nos <strong>cuenta el número de filas</strong> de la tabla, así que vamos a <strong>usar la misma función pero indicándole la variable</strong>.</p>
<div class="sourceCode" id="cb961"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tabla_freq</span> <span class="op">&lt;-</span> <span class="va">starwars_nueva</span> <span class="op">%&gt;%</span> <span class="fu">count</span><span class="op">(</span><span class="va">n_films</span><span class="op">)</span>
<span class="va">tabla_freq</span></code></pre></div>
<pre><code>## # A tibble: 7 × 2
##   n_films     n
##     &lt;int&gt; &lt;int&gt;
## 1       1    46
## 2       2    18
## 3       3    13
## 4       4     2
## 5       5     5
## 6       6     2
## 7       7     1</code></pre>
<p>Esa columna <code>n</code> es lo que conocemos como <strong>frecuencias absolutas</strong>, el <strong>número de veces</strong> que la variable toma dicha valor. También es posible <strong>calcular las frecuencias absolutas</strong> por varias variables a la vez (algo similar a una <strong>tabla de contigencia</strong> aunque en otro formato).</p>
<div class="sourceCode" id="cb963"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars_nueva</span> <span class="op">%&gt;%</span> <span class="fu">count</span><span class="op">(</span><span class="va">sex</span>, <span class="va">gender</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   sex            gender        n
##   &lt;chr&gt;          &lt;chr&gt;     &lt;int&gt;
## 1 female         feminine     16
## 2 hermaphroditic masculine     1
## 3 male           masculine    60
## 4 none           feminine      1
## 5 none           masculine     5
## 6 &lt;NA&gt;           &lt;NA&gt;          4</code></pre>
<p><strong>¿Cómo seguir construyendo nuestra tabla de frecuencias en <code>tabla_freq</code>?</strong> Necesitamos añadir una columna <code>N_i</code> de <strong>frecuencia absoluta acumulada</strong>, una columna que nos diga el <strong>número de personajes que han hecho un número de películas igual o menor</strong> que el indicado.</p>
<div class="sourceCode" id="cb965"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Construimos de cero</span>
<span class="va">tabla_freq</span> <span class="op">&lt;-</span> <span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="co"># n: frecuencia absoluta</span>
  <span class="fu">count</span><span class="op">(</span><span class="va">n_films</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="co"># N_i: frecuencia absoluta acumulada</span>
  <span class="fu">mutate</span><span class="op">(</span>N_i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="co"># cumsum calcula la suma acumulada</span>
<span class="va">tabla_freq</span></code></pre></div>
<pre><code>## # A tibble: 7 × 3
##   n_films     n   N_i
##     &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1       1    46    46
## 2       2    18    64
## 3       3    13    77
## 4       4     2    79
## 5       5     5    84
## 6       6     2    86
## 7       7     1    87</code></pre>
<p>También <strong>necesitamos otras dos columnas</strong> <code>f_i</code> y <code>F_i</code>, de <strong>frecuencias relativas</strong> (no acumulada y acumulada, respectivamente), que nos indica lo mismo que las dos primeras columnas pero en <strong>proporción</strong> respecto a los datos.</p>
<div class="sourceCode" id="cb967"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Construimos de cero</span>
<span class="va">tabla_freq</span> <span class="op">&lt;-</span> <span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="co"># n: frecuencia absoluta</span>
  <span class="fu">count</span><span class="op">(</span><span class="va">n_films</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="co"># N_i: frecuencia absoluta acumulada</span>
  <span class="fu">mutate</span><span class="op">(</span>N_i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co"># cumsum calcula la suma acumulada</span>
  <span class="fu">mutate</span><span class="op">(</span>f_i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/prop.table.html">prop.table</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>, <span class="co"># prop.table nos devuelve proporciones</span>
         F_i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">f_i</span><span class="op">)</span><span class="op">)</span>
<span class="va">tabla_freq</span></code></pre></div>
<pre><code>## # A tibble: 7 × 5
##   n_films     n   N_i    f_i   F_i
##     &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1       1    46    46 0.529  0.529
## 2       2    18    64 0.207  0.736
## 3       3    13    77 0.149  0.885
## 4       4     2    79 0.0230 0.908
## 5       5     5    84 0.0575 0.966
## 6       6     2    86 0.0230 0.989
## 7       7     1    87 0.0115 1</code></pre>
<p>Esas <strong>frecuencias relativas</strong> quizás querramos tenerlas expresadas en <strong>porcentajes</strong> en lugar de en proporciones.</p>
<div class="sourceCode" id="cb969"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Pasamos frecuencias relativas a porcentajes</span>
<span class="va">tabla_freq</span> <span class="op">%&gt;%</span> <span class="fu">mutate</span><span class="op">(</span>f_i <span class="op">=</span> <span class="va">f_i</span> <span class="op">*</span> <span class="fl">100</span>,
                      F_i <span class="op">=</span> <span class="va">F_i</span> <span class="op">*</span> <span class="fl">100</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 5
##   n_films     n   N_i   f_i   F_i
##     &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1       1    46    46 52.9   52.9
## 2       2    18    64 20.7   73.6
## 3       3    13    77 14.9   88.5
## 4       4     2    79  2.30  90.8
## 5       5     5    84  5.75  96.6
## 6       6     2    86  2.30  98.9
## 7       7     1    87  1.15 100</code></pre>
<p>Por último, con la tabla <code>tabla_freq</code> expresando las frecuencias relativas en proporciones, vamos a cambiar el nombre de las columnas para que tengan los <strong>típicos nombres de una tabla de frecuencias</strong>.</p>
<div class="sourceCode" id="cb971"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Renombramos</span>
<span class="va">tabla_freq</span> <span class="op">&lt;-</span> <span class="va">tabla_freq</span> <span class="op">%&gt;%</span>
  <span class="fu">rename</span><span class="op">(</span>n_i <span class="op">=</span> <span class="va">n</span>, x_i <span class="op">=</span> <span class="va">n_films</span><span class="op">)</span>
<span class="va">tabla_freq</span></code></pre></div>
<pre><code>## # A tibble: 7 × 5
##     x_i   n_i   N_i    f_i   F_i
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1     1    46    46 0.529  0.529
## 2     2    18    64 0.207  0.736
## 3     3    13    77 0.149  0.885
## 4     4     2    79 0.0230 0.908
## 5     5     5    84 0.0575 0.966
## 6     6     2    86 0.0230 0.989
## 7     7     1    87 0.0115 1</code></pre>
<div id="htmlwidget-000ca82dd9095120b9e0" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-000ca82dd9095120b9e0">{"x":{"filter":"none","caption":"<caption>Tabla de frecuencias del número de películas en las que aparecen los personajes de la saga.<\/caption>","data":[[1,2,3,4,5,6,7],[46,18,13,2,5,2,1],[46,64,77,79,84,86,87],[0.528735632183908,0.206896551724138,0.149425287356322,0.0229885057471264,0.0574712643678161,0.0229885057471264,0.0114942528735632],[0.528735632183908,0.735632183908046,0.885057471264368,0.908045977011494,0.96551724137931,0.988505747126437,1]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>x_i<\/th>\n      <th>n_i<\/th>\n      <th>N_i<\/th>\n      <th>f_i<\/th>\n      <th>F_i<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"scrollX":true,"fixedColumns":{"leftColumns":1},"headerCallback":"function(thead) {\n  $(thead).css('font-size', '0.95em');\n}","language":{"url":"//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json"},"columnDefs":[{"targets":3,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \".\", \".\");\n  }"},{"targets":4,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \".\", \".\");\n  }"},{"className":"dt-right","targets":[0,1,2,3,4]}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":["options.headerCallback","options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script><p>Con esta tabla podemos <strong>calcular por ejemplo la media</strong> <span class="math inline">\(\overline{x}\)</span> <strong>usando el resumen que tenemos guardado</strong> (como se suele - o solía - hacer cuando se tiene que realizar «a mano» un ejercicio de este tipo en los primeros cursos de estadística).</p>
<p><span class="math display">\[\overline{x} = \frac{1}{N} \sum_{i=1}^{k} n_i x_i = \sum_{i=1}^{k} f_i x_i\]</span></p>
<div class="sourceCode" id="cb973"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidyverse/glue">glue</a></span><span class="op">)</span>

<span class="co"># Renombramos</span>
<span class="va">tabla_freq</span> <span class="op">&lt;-</span> <span class="va">tabla_freq</span> <span class="op">%&gt;%</span> <span class="fu">mutate</span><span class="op">(</span>f_i_x_i <span class="op">=</span> <span class="va">f_i</span> <span class="op">*</span> <span class="va">x_i</span><span class="op">)</span>
<span class="va">media</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tabla_freq</span><span class="op">$</span><span class="va">f_i_x_i</span><span class="op">)</span>
<span class="fu"><a href="https://docs.ropensci.org/skimr/reference/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/glue/man/glue.html">glue</a></span><span class="op">(</span><span class="st">"La media de películas es {round(media, 3)}"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## La media de películas es 1.989</code></pre>
<p> </p>
<p><strong>¿Cómo construir una tabla similar para variables continuas?</strong> La metodología sería la misma solo que antes debemos <strong>agrupar los datos</strong> (por ejemplo, de la variable <code>height</code>) en <strong>subintervalos</strong>.</p>
<div class="sourceCode" id="cb975"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Construimos de cero</span>
<span class="va">tabla_freq_continua</span> <span class="op">&lt;-</span>
  <span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="co"># agrupamos los datos en tramos de 20 en 20</span>
  <span class="fu">mutate</span><span class="op">(</span>intervalo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">height</span>, breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">65</span>, <span class="fl">265</span>, by <span class="op">=</span> <span class="fl">20</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="co"># n: frecuencia absoluta</span>
  <span class="fu">count</span><span class="op">(</span><span class="va">intervalo</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="co"># N_i: frecuencia absoluta acumulada</span>
  <span class="fu">mutate</span><span class="op">(</span>N_i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co"># cumsum calcula la suma acumulada</span>
  <span class="fu">mutate</span><span class="op">(</span>f_i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/prop.table.html">prop.table</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>, <span class="co"># prop.table nos devuelve proporciones</span>
         F_i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">f_i</span><span class="op">)</span><span class="op">)</span>
<span class="va">tabla_freq_continua</span></code></pre></div>
<pre><code>## # A tibble: 11 × 5
##    intervalo     n   N_i    f_i    F_i
##    &lt;fct&gt;     &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 (65,85]       2     2 0.0230 0.0230
##  2 (85,105]      5     7 0.0575 0.0805
##  3 (105,125]     2     9 0.0230 0.103 
##  4 (125,145]     1    10 0.0115 0.115 
##  5 (145,165]     9    19 0.103  0.218 
##  6 (165,185]    34    53 0.391  0.609 
##  7 (185,205]    19    72 0.218  0.828 
##  8 (205,225]     5    77 0.0575 0.885 
##  9 (225,245]     3    80 0.0345 0.920 
## 10 (245,265]     1    81 0.0115 0.931 
## 11 &lt;NA&gt;          6    87 0.0690 1</code></pre>
<p>El problema es que <strong>cuando agrupamos los datos de una varibale continua en subintervalos</strong>, aunque nos sirva como <strong>resumen</strong> para tener una idea de como se comporta nuestra variable (y sea <strong>algo necesario para, por ejemplo, construir un «histograma discretizado»</strong>), a la hora de calcular sus estadísticas perdemos información ya que todos los elementos que cae en un intervalo se les <strong>imputará un único valor: la marca de clase, que normalmente es el punto medio del intervalo</strong>.</p>
<p>Vamos a <strong>calcular resúmenes numéricos</strong> de las variables sin agrupar aprovechando que <code>R</code> el trabajo por nosotros/as.</p>
</div>
<div id="resúmenes-numéricos-summarise-y-skimr-y-por-grupos-group_by" class="section level2">
<h2>
<span class="header-section-number">14.2</span> Resúmenes numéricos (summarise y skimr) y por grupos (group_by)<a class="anchor" aria-label="anchor" href="#res%C3%BAmenes-num%C3%A9ricos-summarise-y-skimr-y-por-grupos-group_by"><i class="fas fa-link"></i></a>
</h2>
<p>Antes de pasar a ver <strong>cómo generar nuestras propias estadísticas de los datos</strong>, veamos la funcionalidad de un maravilloso paquete llamado <a href="https://docs.ropensci.org/skimr/">skimr</a>, que nos permite tener en un vistazo un <strong>resumen numérico</strong> muy completo de nuestros datos, con <strong>histograma/diagrama de barras incluido</strong>.</p>
<div class="sourceCode" id="cb977"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/skimr/">skimr</a></span><span class="op">)</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:unnamed-chunk-356">Tabla 14.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">87</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">14</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">list</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: character</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">name</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3</td>
<td align="right">21</td>
<td align="right">0</td>
<td align="right">87</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">hair_color</td>
<td align="right">5</td>
<td align="right">0.94</td>
<td align="right">4</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">12</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">skin_color</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3</td>
<td align="right">19</td>
<td align="right">0</td>
<td align="right">31</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">eye_color</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">15</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">4</td>
<td align="right">0.95</td>
<td align="right">4</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">gender</td>
<td align="right">4</td>
<td align="right">0.95</td>
<td align="right">8</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">homeworld</td>
<td align="right">10</td>
<td align="right">0.89</td>
<td align="right">4</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">48</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">species</td>
<td align="right">4</td>
<td align="right">0.95</td>
<td align="right">3</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">37</td>
<td align="right">0</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: list</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">n_unique</th>
<th align="right">min_length</th>
<th align="right">max_length</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">films</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">24</td>
<td align="right">1</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">vehicles</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">starships</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">17</td>
<td align="right">0</td>
<td align="right">5</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: numeric</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">height</td>
<td align="right">6</td>
<td align="right">0.93</td>
<td align="right">174.36</td>
<td align="right">34.77</td>
<td align="right">66</td>
<td align="right">167.0</td>
<td align="right">180</td>
<td align="right">191.0</td>
<td align="right">264</td>
<td align="left">▁▁▇▅▁</td>
</tr>
<tr class="even">
<td align="left">mass</td>
<td align="right">28</td>
<td align="right">0.68</td>
<td align="right">97.31</td>
<td align="right">169.46</td>
<td align="right">15</td>
<td align="right">55.6</td>
<td align="right">79</td>
<td align="right">84.5</td>
<td align="right">1358</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">birth_year</td>
<td align="right">44</td>
<td align="right">0.49</td>
<td align="right">87.57</td>
<td align="right">154.69</td>
<td align="right">8</td>
<td align="right">35.0</td>
<td align="right">52</td>
<td align="right">72.0</td>
<td align="right">896</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table></div>
<p>Dicho resumen nos proporciona:</p>
<ul>
<li><p>Variables de tipo <strong>caracter</strong>: <code>n_missing</code> (número de ausentes), <code>complete_rate</code> (proporción de datos sin ausentes), <code>min/max</code> y <code>n_unique</code> (número de valores únicos).</p></li>
<li><p>Variables de tipo <strong>lista</strong>: <code>n_missing</code> (número de ausentes), <code>complete_rate</code> (proporción de datos sin ausentes), <code>n_unique</code> (número de valores únicos) y <code>min_length/max_length</code> (longitud mínimo/máxima de las listas).</p></li>
<li><p>Variables de tipo <strong>numérico</strong>: <code>n_missing</code> (número de ausentes), <code>complete_rate</code> (proporción de datos sin ausentes), <code>mean/sd</code> (media y cuasidesviación típica), <code>p0/p25/p50/p75/p100</code> (cuartiles, percentiles 0%-25%-50%-75%-100%, valores que nos dividen nuestro conjunto en 4 trozos) e <code>hist</code> (una especie de histograma/barras sencillo).</p></li>
</ul>
<p>Este resumen no solo podemos visualizarlo sino que podemos guardarlo para exportarlo por ejemplo en un <code>.csv</code>.</p>
<div class="sourceCode" id="cb978"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/skimr/">skimr</a></span><span class="op">)</span>
<span class="va">resumen_skim</span> <span class="op">&lt;-</span> <span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p>Sin embargo, aunque el resumen es bastante completo, muchas veces <strong>querremos generar nuestras propias estadísticas o resúmenes numéricos</strong>, y para eso vamos a aplicar <code>summarise()</code>, que nos calculará estadísticas de nuestros datos. Por ejemplo, vamos a <strong>calcular las medidas de centralización (media-mediana-moda)</strong>. Para las dos primeras basta con aplicar las funciones correspondientes.</p>
<div class="sourceCode" id="cb979"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span>,
                       mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media mediana
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1    NA      NA</code></pre>
<p>Como ves nos <strong>devuelve un dato ausente</strong> ya que al existir datos ausentes en la variables, <strong>la media también lo es</strong>. Para evitar ese problema <strong>podemos hacer dos cosas</strong>: eliminar antes los ausentes o indicarle en la propia media y mediana que haga el cálculo ignorando los valores <code>NA</code>.</p>
<div class="sourceCode" id="cb981"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Primero eliminamos NA</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu">drop_na</span><span class="op">(</span><span class="va">mass</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span>, mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media mediana
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1  97.3      79</code></pre>
<div class="sourceCode" id="cb983"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Al realizar el cálculo los ignora</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media mediana
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1  97.3      79</code></pre>
<p>La <strong>media</strong> es una medida de centralización basada en el valor que nos <strong>minimiza el promedio de desviaciones al cuadrado (varianza)</strong> y solo se puede calcular para <strong>variables cuantitativas (discretas o continuas)</strong>.</p>
<div class="sourceCode" id="cb985"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Media de todas las cuantitativas</span>
<span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   media$height $mass $birth_year $n_films
##          &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;
## 1         174.  97.3        87.6     1.99</code></pre>
<p>La <strong>mediana</strong> se define como el <strong>valor que ocupa el centro de los datos CUANDO LOS ORDENAMOS de menor a mayor</strong>, un valor que nos deja por debajo al menos el 50% y por encima al menos el 50%.</p>
<div class="sourceCode" id="cb987"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Media y mediana de todas las cuantitativas</span>
<span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">median</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media$height $mass $birth_year $n_films mediana$height $mass $birth_year
##          &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;          &lt;int&gt; &lt;dbl&gt;       &lt;dbl&gt;
## 1         174.  97.3        87.6     1.99            180    79          52</code></pre>
<p>La <strong>mediana también se puede calcular para variables cualitativas ordinales (categorías que se puedan ordenar)</strong>. Vamos a construir una variable que sea «muy bajo-bajo-medio-alto-muy alto» según la estatura, y calcular la mediana para dichas categorías.</p>
<div class="sourceCode" id="cb989"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">categorias</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"muy bajo"</span>, <span class="st">"bajo"</span>, <span class="st">"medio"</span>, <span class="st">"alto"</span>, <span class="st">"muy alto"</span><span class="op">)</span>
<span class="va">starwars_talla</span> <span class="op">&lt;-</span> 
  <span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>talla <span class="op">=</span>
           <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">height</span>, breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="cn">Inf</span>, <span class="fl">80</span>, <span class="fl">120</span>, <span class="fl">160</span>, <span class="fl">190</span>, <span class="cn">Inf</span><span class="op">)</span>,
               labels <span class="op">=</span> <span class="va">categorias</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Mediana (hay que pasárselo como número)</span>
<span class="va">starwars_talla</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>mediana <span class="op">=</span>
              <span class="va">categorias</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">talla</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   mediana
##   &lt;chr&gt;  
## 1 alto</code></pre>
<p>Para la <strong>moda tenemos algún problema mayor</strong> ya que no hay un función en los paquetes <code>{base}</code> para su cálculo, así que para ello <strong>usaremos el paquete <a href="https://github.com/paulponcet/modeest">modeest</a></strong>: la función <code><a href="https://rdrr.io/pkg/statip/man/mfv.html">mfv()</a></code> nos calcula la <strong>moda exacta</strong> de una variable numérica discreta o cuantitativa (busca los valores más repetidos), la función <code><a href="https://rdrr.io/pkg/modeest/man/mlv.html">mlv()</a></code> nos calcula la <strong>moda estimada</strong> de una variable numérica continua.</p>
<div class="sourceCode" id="cb991"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/paulponcet/modeest">modeest</a></span><span class="op">)</span>

<span class="co"># Media y mediana y moda de mass y n_films</span>
<span class="va">resumen</span> <span class="op">&lt;-</span> 
  <span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu">across</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mass</span>, <span class="va">n_films</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu">across</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mass</span>, <span class="va">n_films</span><span class="op">)</span>, <span class="va">median</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            moda_n_films <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/statip/man/mfv.html">mfv</a></span><span class="op">(</span><span class="va">n_films</span>, na_rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            moda_mass <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/modeest/man/mlv.html">mlv</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="va">resumen</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   media$mass $n_films mediana$mass $n_films moda_n_films moda_mass
##        &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;    &lt;int&gt;        &lt;int&gt;     &lt;dbl&gt;
## 1       97.3     1.99           79        1            1      80.3</code></pre>
<p>Fíjate que el resumen ha agrupado todas las modas y medianas que hemos calculado a la vez: <strong>la salida de nuestro resumen es una lista, con tablas a su vez dentro</strong>.</p>
<p>De la misma manera podemos pedirle que nos calcule <strong>medidas de dispersión (varianza, desv. típica y cv, cómo de dispersos están los datos respecto a un centro, normalmente la media)</strong> y <strong>medidas de localización (percentiles)</strong>.</p>
<div class="sourceCode" id="cb993"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            moda <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/modeest/man/mlv.html">mlv</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            var <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            cv <span class="op">=</span> <span class="va">sd</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">media</span><span class="op">)</span>,
            p13 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">mass</span>, probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.13</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            p87 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">mass</span>, probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.87</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   media mediana  moda    var    sd    cv   p13   p87
##   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  97.3      79  80.3 28716.  169.  1.74  46.6  111.</code></pre>
<p>Haciendo uso de cosas ya vistas podemos, por ejemplo, <strong>calcular el coeficiente de variación (CV)</strong> de todas las variables numéricas para poder decidir cual es más o meno dispersa.</p>
<div class="sourceCode" id="cb995"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resumen</span> <span class="op">&lt;-</span> 
  <span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media <span class="op">=</span> <span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            var <span class="op">=</span> <span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">var</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            cv <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">var</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">media</span><span class="op">)</span><span class="op">)</span>
<span class="va">resumen</span><span class="op">$</span><span class="va">media</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   height  mass birth_year
##    &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
## 1   174.  97.3       87.6</code></pre>
<div class="sourceCode" id="cb997"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resumen</span><span class="op">$</span><span class="va">var</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   height   mass birth_year
##    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
## 1  1209. 28716.     23929.</code></pre>
<div class="sourceCode" id="cb999"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resumen</span><span class="op">$</span><span class="va">cv</span> <span class="co"># más homogénea la altura por tener menos CV.</span></code></pre></div>
<pre><code>##      height     mass birth_year
## 1 0.1994197 1.741382   1.766587</code></pre>
<div id="agrupando-datos-group_by" class="section level3">
<h3>
<span class="header-section-number">14.2.1</span> Agrupando datos: group_by<a class="anchor" aria-label="anchor" href="#agrupando-datos-group_by"><i class="fas fa-link"></i></a>
</h3>
<p>Una de las <strong>funcionalidades más potentes es la opción de añadir antes una agrupación</strong> con <code>group_by()</code>. Esta función per se no cambia los datos sino que cambia la forma en la que se aplicarán las funciones posteriores, realizándose por <strong>desagregadas grupos</strong>.</p>
<p>Imagina que queremos calcular la <strong>media de altura y peso</strong> de cada personaje PERO desagregada por cada una de las clases que tenemos en la variable <code>sex</code>.</p>
<div class="sourceCode" id="cb1001"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu">group_by</span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media_altura <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">height</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            media_peso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   sex            media_altura media_peso
##   &lt;chr&gt;                 &lt;dbl&gt;      &lt;dbl&gt;
## 1 female                 169.       54.7
## 2 hermaphroditic         175      1358  
## 3 male                   179.       81.0
## 4 none                   131.       69.8
## 5 &lt;NA&gt;                   181.       48</code></pre>
<p>Lo que obtenemos no es la media de todos los personajes sino la <strong>media desagregada por grupo</strong>, grupo marcado por la variable <code>sex</code>. Las <strong>agrupaciones pueden estar en función de varias variables</strong> a la vez.</p>
<div class="sourceCode" id="cb1003"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu">group_by</span><span class="op">(</span><span class="va">sex</span>, <span class="va">gender</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span>media_altura <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">height</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            media_peso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   sex            gender    media_altura media_peso
##   &lt;chr&gt;          &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
## 1 female         feminine          169.       54.7
## 2 hermaphroditic masculine         175      1358  
## 3 male           masculine         179.       81.0
## 4 none           feminine           96       NaN  
## 5 none           masculine         140        69.8
## 6 &lt;NA&gt;           &lt;NA&gt;              181.       48</code></pre>
<p>Dicha función también es muy útil cuando queremos <strong>realizar un filtro de registros en base al número de cada clase</strong>: por ejemplo, vamos a filtrar los registros que pertenezcan a una clase de <code>sex</code> que tenga al menos 10 individuos dentro de dicho grupo.</p>
<div class="sourceCode" id="cb1005"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">count</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
##   sex                n
##   &lt;chr&gt;          &lt;int&gt;
## 1 female            16
## 2 hermaphroditic     1
## 3 male              60
## 4 none               6
## 5 &lt;NA&gt;               4</code></pre>
<p>Si te fijas solo deberíamos filtrar los registros que sean <code>female</code> y <code>male</code>. Vamos a hacerlo de forma automática en base a dicho <strong>umbral</strong>.</p>
<div class="sourceCode" id="cb1007"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Podemos filtrar por grupos solo aquellos que superen un</span>
<span class="co"># un umbral mínimo</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span> 
  <span class="fu">group_by</span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu">n</span><span class="op">(</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 76 × 14
##    name    height  mass hair_color  skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Luke S…    172    77 blond       fair       blue            19   male  mascu…
##  2 Darth …    202   136 none        white      yellow          41.9 male  mascu…
##  3 Leia O…    150    49 brown       light      brown           19   fema… femin…
##  4 Owen L…    178   120 brown, grey light      blue            52   male  mascu…
##  5 Beru W…    165    75 brown       light      blue            47   fema… femin…
##  6 Biggs …    183    84 black       light      brown           24   male  mascu…
##  7 Obi-Wa…    182    77 auburn, wh… fair       blue-gray       57   male  mascu…
##  8 Anakin…    188    84 blond       fair       blue            41.9 male  mascu…
##  9 Wilhuf…    180    NA auburn, gr… fair       blue            64   male  mascu…
## 10 Chewba…    228   112 brown       unknown    blue           200   male  mascu…
## # … with 66 more rows, and 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;,
## #   films &lt;list&gt;, vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Para comprobar rápidamente que efectivamente solo ha filtrado aquellos grupos con más de 10 elementos en ellos podemos <strong>añadir <code>count()</code></strong>.</p>
<div class="sourceCode" id="cb1009"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> 
  <span class="fu">group_by</span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu">n</span><span class="op">(</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">count</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   sex        n
##   &lt;chr&gt;  &lt;int&gt;
## 1 female    16
## 2 male      60</code></pre>
<p>Los resúmenes y las agrupaciones podemos <strong>combinarlas de todas las formas que nos imaginemos</strong>, por ejemplo, calculando la media desagregada por sexo y género pero solo de las variables numéricas.</p>
<div class="sourceCode" id="cb1011"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="co"># doble agrupación</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">sex</span>, <span class="va">gender</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarise</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   sex            gender    height   mass birth_year
##   &lt;chr&gt;          &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
## 1 female         feminine    169.   54.7       47.2
## 2 hermaphroditic masculine   175  1358        600  
## 3 male           masculine   179.   81.0       85.5
## 4 none           feminine     96   NaN        NaN  
## 5 none           masculine   140    69.8       53.3
## 6 &lt;NA&gt;           &lt;NA&gt;        181.   48         62</code></pre>
</div>
<div id="rowwise-operaciones-por-filas" class="section level3">
<h3>
<span class="header-section-number">14.2.2</span> Rowwise: operaciones por filas<a class="anchor" aria-label="anchor" href="#rowwise-operaciones-por-filas"><i class="fas fa-link"></i></a>
</h3>
<p>Por último veamos un ejemplo de una <strong>opción muy útil usada antes de una operación que es</strong> <code>rowwise()</code>: toda operación que venga después se aplicará <strong>en cada fila por separado</strong>. Para el ejemplo vamos a definir un fichero <em>dummy</em> de notas en mates, lengua y dibujo de 50 alumnos. Para ello usamos la función <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code>: le decimos que seleccione aleatoriamente <code>size = 50</code> notas de un conjunto de notas posibles (<code>0:10</code>), y que lo haga con reemplazamiento (<code>replace = TRUE</code>, es decir, que dos alumnos puedan tener la misma nota)</p>
<div class="sourceCode" id="cb1013"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">notas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tibble/man/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"mates"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, size <span class="op">=</span> <span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                <span class="st">"lengua"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, size <span class="op">=</span> <span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                <span class="st">"dibujo"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, size <span class="op">=</span> <span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="va">notas</span></code></pre></div>
<pre><code>## # A tibble: 50 × 3
##    mates lengua dibujo
##    &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
##  1     0      7      5
##  2     8      2      1
##  3     9      7      0
##  4     9      9      9
##  5     1      6      5
##  6     0      1      4
##  7     9      5      1
##  8     0      3      3
##  9     1      7      6
## 10     7      2      5
## # … with 40 more rows</code></pre>
<p>Una vez que tenemos 3 notas aleatorias por cada uno de los 50 alumnos, <strong>¿qué sucede si yo quiero calcular la nota media del curso?</strong></p>
<div class="sourceCode" id="cb1015"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">notas</span> <span class="op">%&gt;%</span> <span class="fu">mutate</span><span class="op">(</span>media_curso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mates</span>, <span class="va">lengua</span>, <span class="va">dibujo</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 50 × 4
##    mates lengua dibujo media_curso
##    &lt;int&gt;  &lt;int&gt;  &lt;int&gt;       &lt;dbl&gt;
##  1     0      7      5        4.64
##  2     8      2      1        4.64
##  3     9      7      0        4.64
##  4     9      9      9        4.64
##  5     1      6      5        4.64
##  6     0      1      4        4.64
##  7     9      5      1        4.64
##  8     0      3      3        4.64
##  9     1      7      6        4.64
## 10     7      2      5        4.64
## # … with 40 more rows</code></pre>
<p>Como ves si aplicamos la media de las tres variables, en cada fila el valor de <code>media_curso</code> es idéntico ya que nos ha hecho la <strong>media global</strong>: ha tomado las 50 filas, las 3 columnas, y ha hecho la media de 150 datos. Cuando en realidad a nosotros nos gustaría <strong>sacar una media por registro</strong>, que para cada alumno tengamos la media de las asignaturas.</p>
<div class="sourceCode" id="cb1017"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Aplicado por fila</span>
<span class="va">notas</span> <span class="op">%&gt;%</span> <span class="fu">rowwise</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>media_curso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mates</span>, <span class="va">lengua</span>, <span class="va">dibujo</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 50 × 4
## # Rowwise: 
##    mates lengua dibujo media_curso
##    &lt;int&gt;  &lt;int&gt;  &lt;int&gt;       &lt;dbl&gt;
##  1     0      7      5        4   
##  2     8      2      1        3.67
##  3     9      7      0        5.33
##  4     9      9      9        9   
##  5     1      6      5        4   
##  6     0      1      4        1.67
##  7     9      5      1        5   
##  8     0      3      3        2   
##  9     1      7      6        4.67
## 10     7      2      5        4.67
## # … with 40 more rows</code></pre>
<p>Solos nos falta poner la guinda a lo aprendido a esta introducción: <strong>vamos a ver como podemos relacionar dos conjuntos de datos distintos entre sí</strong>.</p>
</div>
</div>
<div id="relacionar-datos-joins" class="section level2">
<h2>
<span class="header-section-number">14.3</span> Relacionar datos (joins)<a class="anchor" aria-label="anchor" href="#relacionar-datos-joins"><i class="fas fa-link"></i></a>
</h2>
<p>Una de las <strong>opciones más comunes para trabajar con datos</strong> es tener a nuestra disposición diversas tablas, con alguno o varios de los campos en común, y nos interesa a veces <strong>cruzar datos</strong> de ambos para tener una información más completa con el conjunto de las tablas. Es lo que se conoce en ciencia de datos e informática como <strong>hacer un <em>join</em> de tablas</strong>. Para ese cruce será <strong>indispensable que haya uno o varios campos clave</strong>, campos que sirvan para identificar unívocamente cada registro (por ejemplo, DNI).</p>
<div class="figure">
<span style="display:block;" id="fig:joins"></span>
<img src="img/sql-joins.jpg" alt="Esquema con los principales tipos de join, extraído de &lt;https://estradawebgroup.com/Post/-Que-es-y-para-que-sirve-SQL-Joins-/4278&gt;" width="450"><p class="caption">
Imagen/gráfica 14.1: Esquema con los principales tipos de join, extraído de <a href="https://estradawebgroup.com/Post/-Que-es-y-para-que-sirve-SQL-Joins-/4278" class="uri">https://estradawebgroup.com/Post/-Que-es-y-para-que-sirve-SQL-Joins-/4278</a>
</p>
</div>
<p>Existen principalmente <strong>cuatro tipos de cruces</strong> si pensamos en cruzar un conjunto <code>A</code> con otro conjunto <code>B</code>:</p>
<ul>
<li><p><strong>Inner join</strong>: solo nos quedamos con las <strong>filas que tengan correspondencia en ambas tablas</strong> (personas cuyo DNI aparezca en ambas tablas, por ejemplo).</p></li>
<li><p><strong>Left (outer) join</strong>: nos quedamos con <strong>todas las filas de <code>A</code></strong>, buscando que registros de dicha tabla están también en <code>B</code>, completando los datos de esta tabla para esos registros.</p></li>
<li><p><strong>Right (outer) join</strong>: nos quedamos con <strong>todas las filas de <code>B</code></strong>, buscando que registros de dicha tabla están también en <code>A</code>, completando los datos de esta tabla para esos registros.</p></li>
<li><p><strong>Full join</strong>: nos quedamos con <strong>todas las filas de <code>A</code> y <code>B</code></strong>, tengan o no correspondencia en la otra tabla (si no está en una de ellas, las columnas correspondientes quedarán como campo ausente).</p></li>
</ul>
<p>Esos <strong>campos clave (keys)</strong> serán las columnas que usaremos para definir los cruces. Para los ejemplos usaremos las tablas del paquete <a href="https://github.com/hadley/nycflights13">nycflights13</a>.</p>
<div class="sourceCode" id="cb1019"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hadley/nycflights13">nycflights13</a></span><span class="op">)</span></code></pre></div>
<p>Dicho paquete cuenta con las siguientes <strong>tablas</strong>:</p>
<ul>
<li>
<code>airlines</code>: nombre de la aerolínea (con su abreviatura).</li>
<li>
<code>airports</code>: datos de aeropuertos (nombres, longitud, latitud, altitud, etc).</li>
<li>
<code>flights</code>: datos de vuelos (con <code>tailnum</code> como marca de idenfiticación).</li>
<li>
<code>planes</code>: datos de los aviones.</li>
<li>
<code>weather</code>: datos meteorológicos horarios de las estaciones LGA, JFK y EWR.</li>
</ul>
<p>Veamos un ejemplo: imagina que queremos <strong>completar en la tabla de vuelos los datos de cada una de las aerolíneas que operan dichos vuelos</strong>. Vamos a seleccionar unas pocas columnas para que sea más fácil de visualizar.</p>
<div class="sourceCode" id="cb1020"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Seleccionamos antes columnas para que sea más corto</span>
<span class="va">flights_filtrada</span> <span class="op">&lt;-</span> <span class="va">flights</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">year</span><span class="op">:</span><span class="va">day</span>, <span class="va">arr_time</span>, <span class="va">carrier</span><span class="op">:</span><span class="va">dest</span><span class="op">)</span>
<span class="va">flights_filtrada</span></code></pre></div>
<pre><code>## # A tibble: 336,776 × 9
##     year month   day arr_time carrier flight tailnum origin dest 
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;
##  1  2013     1     1      830 UA        1545 N14228  EWR    IAH  
##  2  2013     1     1      850 UA        1714 N24211  LGA    IAH  
##  3  2013     1     1      923 AA        1141 N619AA  JFK    MIA  
##  4  2013     1     1     1004 B6         725 N804JB  JFK    BQN  
##  5  2013     1     1      812 DL         461 N668DN  LGA    ATL  
##  6  2013     1     1      740 UA        1696 N39463  EWR    ORD  
##  7  2013     1     1      913 B6         507 N516JB  EWR    FLL  
##  8  2013     1     1      709 EV        5708 N829AS  LGA    IAD  
##  9  2013     1     1      838 B6          79 N593JB  JFK    MCO  
## 10  2013     1     1      753 AA         301 N3ALAA  LGA    ORD  
## # … with 336,766 more rows</code></pre>
<p>Queremos <strong>TODAS las filas de los vuelos</strong>, todos sus registros, pero <strong>añadiendo la información</strong> que tenemos de la aerolínea que opere los vuelos, así que haremos un <strong>LEFT JOIN</strong> de <code>flights</code> vs <code>airlines</code>. El campo común que nos permite cruzarla, la <strong>clave (key)</strong> es el código abreviado de las aerolíneas (variable <code>carrier</code>).</p>
<div class="sourceCode" id="cb1022"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Mismas filas pero con una nueva columna: siempre que sea</span>
<span class="co"># posible el cruce tendrá la info de la aerolínea</span>
<span class="va">l_join_flights_airlines</span> <span class="op">&lt;-</span>
  <span class="va">flights_filtrada</span> <span class="op">%&gt;%</span> <span class="fu">left_join</span><span class="op">(</span><span class="va">airlines</span>, by <span class="op">=</span> <span class="st">"carrier"</span><span class="op">)</span>
<span class="va">l_join_flights_airlines</span></code></pre></div>
<pre><code>## # A tibble: 336,776 × 10
##     year month   day arr_time carrier flight tailnum origin dest  name          
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;         
##  1  2013     1     1      830 UA        1545 N14228  EWR    IAH   United Air Li…
##  2  2013     1     1      850 UA        1714 N24211  LGA    IAH   United Air Li…
##  3  2013     1     1      923 AA        1141 N619AA  JFK    MIA   American Airl…
##  4  2013     1     1     1004 B6         725 N804JB  JFK    BQN   JetBlue Airwa…
##  5  2013     1     1      812 DL         461 N668DN  LGA    ATL   Delta Air Lin…
##  6  2013     1     1      740 UA        1696 N39463  EWR    ORD   United Air Li…
##  7  2013     1     1      913 B6         507 N516JB  EWR    FLL   JetBlue Airwa…
##  8  2013     1     1      709 EV        5708 N829AS  LGA    IAD   ExpressJet Ai…
##  9  2013     1     1      838 B6          79 N593JB  JFK    MCO   JetBlue Airwa…
## 10  2013     1     1      753 AA         301 N3ALAA  LGA    ORD   American Airl…
## # … with 336,766 more rows</code></pre>
<p>Si te fijas ahora tenemos en <code>l_join_flights_airlines</code> las mismas 336776 filas pero con una columna más: la tabla <code>airlines</code> tenía 2 columnas, una la común con <code>flights</code> y en otra la nueva que se ha incorporado a la tabla. <strong>¿Y si en <code>flights</code> había algún vuelo operado por alguna aerolínea que no estuviese en <code>airlines</code>?</strong></p>
<div class="sourceCode" id="cb1024"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Filtramos</span>
<span class="va">l_join_flights_airlines</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">name</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 0 × 10
## # … with 10 variables: year &lt;int&gt;, month &lt;int&gt;, day &lt;int&gt;, arr_time &lt;int&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   name &lt;chr&gt;</code></pre>
<p>En este caso todos los registros de la primera tabla tenían su correspondencia en la segunda tabla. Veamos un ejemplo donde suceda eso, quitándole algunas filas a <code>airlines</code>, quitando las aerolíneas con códigos <code>"B6"</code>.</p>
<div class="sourceCode" id="cb1026"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">airlines_filtrada</span> <span class="op">&lt;-</span> <span class="va">airlines</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="op">(</span><span class="va">carrier</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"B6"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="va">l_join</span> <span class="op">&lt;-</span> <span class="va">flights_filtrada</span> <span class="op">%&gt;%</span> <span class="fu">left_join</span><span class="op">(</span><span class="va">airlines_filtrada</span>, by <span class="op">=</span> <span class="st">"carrier"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">l_join</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">name</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 54635    10</code></pre>
<p>En el anterior ejemplo tenemos 54 635 filas que cuyo nombre está ausente, es decir, 54 635 filas de <code>flights</code> que no tienen correspondencia en la tabla filtrada <code>airlines_filtrada</code>. Ahora las <strong>filas que no han encontrado su <em>match</em> en la segunda tabla están como campo ausente</strong>.</p>
<div class="sourceCode" id="cb1028"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">l_join</span></code></pre></div>
<pre><code>## # A tibble: 336,776 × 10
##     year month   day arr_time carrier flight tailnum origin dest  name          
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;         
##  1  2013     1     1      830 UA        1545 N14228  EWR    IAH   United Air Li…
##  2  2013     1     1      850 UA        1714 N24211  LGA    IAH   United Air Li…
##  3  2013     1     1      923 AA        1141 N619AA  JFK    MIA   American Airl…
##  4  2013     1     1     1004 B6         725 N804JB  JFK    BQN   &lt;NA&gt;          
##  5  2013     1     1      812 DL         461 N668DN  LGA    ATL   Delta Air Lin…
##  6  2013     1     1      740 UA        1696 N39463  EWR    ORD   United Air Li…
##  7  2013     1     1      913 B6         507 N516JB  EWR    FLL   &lt;NA&gt;          
##  8  2013     1     1      709 EV        5708 N829AS  LGA    IAD   ExpressJet Ai…
##  9  2013     1     1      838 B6          79 N593JB  JFK    MCO   &lt;NA&gt;          
## 10  2013     1     1      753 AA         301 N3ALAA  LGA    ORD   American Airl…
## # … with 336,766 more rows</code></pre>
<div class="figure">
<span style="display:block;" id="fig:left-join"></span>
<img src="img/left_join.jpg" alt="Esquema del left join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="400"><p class="caption">
Imagen/gráfica 14.2: Esquema del left join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
<p>La misma lógica para los <strong>RIGHT JOIN</strong> y los <strong>FULL JOIN</strong>. En este último tendremos bastantes datos ausentes, ya que todos los registros que no estén en ambas tablas tendrán una parte de sus variables como <code>NA</code></p>
<div class="sourceCode" id="cb1030"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tabla1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tibble/man/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">7</span>, <span class="st">"valor_1"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"x"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">7</span><span class="op">)</span><span class="op">)</span>
<span class="va">tabla2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tibble/man/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"key_2"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">9</span>, <span class="fl">10</span><span class="op">)</span>,
                 <span class="st">"valor_2"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"x"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">9</span>, <span class="fl">10</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Left</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu">left_join</span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 3
##   key_1 valor_1 valor_2
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
## 1     1 x1      x1     
## 2     2 x2      x2     
## 3     3 x3      &lt;NA&gt;   
## 4     4 x4      &lt;NA&gt;   
## 5     5 x5      x5     
## 6     6 x6      x6     
## 7     7 x7      &lt;NA&gt;</code></pre>
<div class="sourceCode" id="cb1032"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Right</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu">right_join</span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 3
##   key_1 valor_1 valor_2
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
## 1     1 x1      x1     
## 2     2 x2      x2     
## 3     5 x5      x5     
## 4     6 x6      x6     
## 5     0 &lt;NA&gt;    x0     
## 6     9 &lt;NA&gt;    x9     
## 7    10 &lt;NA&gt;    x10</code></pre>
<div class="sourceCode" id="cb1034"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Full</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu">full_join</span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    key_1 valor_1 valor_2
##    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
##  1     1 x1      x1     
##  2     2 x2      x2     
##  3     3 x3      &lt;NA&gt;   
##  4     4 x4      &lt;NA&gt;   
##  5     5 x5      x5     
##  6     6 x6      x6     
##  7     7 x7      &lt;NA&gt;   
##  8     0 &lt;NA&gt;    x0     
##  9     9 &lt;NA&gt;    x9     
## 10    10 &lt;NA&gt;    x10</code></pre>
<div class="figure">
<span style="display:block;" id="fig:right-join"></span>
<img src="img/right_join.jpg" alt="Esquema del right join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="400"><p class="caption">
Imagen/gráfica 14.3: Esquema del right join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
<div class="figure">
<span style="display:block;" id="fig:full-join"></span>
<img src="img/full_join.jpg" alt="Esquema del full join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="400"><p class="caption">
Imagen/gráfica 14.4: Esquema del full join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
<p>Un tipo de join especial son los <strong>INNER JOIN</strong>. Hasta ahora la tabla resultante tenía al menos tantas filas como tuviese la tabla más pequeña en el cruce. En el caso de los <strong>INNER JOIN</strong> vamos a <strong>reducir el tamaño</strong> ya que solo nos quedaremos con <strong>aquellos registros que podamos encontrar en ambas</strong>, de forma que <strong>el cruce nunca generará datos ausentes</strong>.</p>
<div class="sourceCode" id="cb1036"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Inner</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu">inner_join</span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   key_1 valor_1 valor_2
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
## 1     1 x1      x1     
## 2     2 x2      x2     
## 3     5 x5      x5     
## 4     6 x6      x6</code></pre>
<div class="figure">
<span style="display:block;" id="fig:inner-join"></span>
<img src="img/inner_join.png" alt="Esquema del inner join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="338"><p class="caption">
Imagen/gráfica 14.5: Esquema del inner join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
</div>
<div id="ejercicios-9" class="section level2">
<h2>
<span class="header-section-number">14.4</span> 📝 Ejercicios<a class="anchor" aria-label="anchor" href="#ejercicios-9"><i class="fas fa-link"></i></a>
</h2>
<p>en breve</p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="tidyverse.html"><span class="header-section-number">13</span> Explorando los datos: incursión a tidyverse</a></div>
<div class="next"><a href="ggplot2.html"><span class="header-section-number">15</span> Visualizando datos: incursión a ggplot2</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#resumenes"><span class="header-section-number">14</span> Resumiendo y relacionado los datos</a></li>
<li><a class="nav-link" href="#tablas-de-frecuencias"><span class="header-section-number">14.1</span> Tablas de frecuencias</a></li>
<li>
<a class="nav-link" href="#res%C3%BAmenes-num%C3%A9ricos-summarise-y-skimr-y-por-grupos-group_by"><span class="header-section-number">14.2</span> Resúmenes numéricos (summarise y skimr) y por grupos (group_by)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#agrupando-datos-group_by"><span class="header-section-number">14.2.1</span> Agrupando datos: group_by</a></li>
<li><a class="nav-link" href="#rowwise-operaciones-por-filas"><span class="header-section-number">14.2.2</span> Rowwise: operaciones por filas</a></li>
</ul>
</li>
<li><a class="nav-link" href="#relacionar-datos-joins"><span class="header-section-number">14.3</span> Relacionar datos (joins)</a></li>
<li><a class="nav-link" href="#ejercicios-9"><span class="header-section-number">14.4</span> 📝 Ejercicios</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/dadosdelaplace/intro-R/blob/master/13-resumenes.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/dadosdelaplace/intro-R/edit/master/13-resumenes.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Aprendiendo R sin morir en el intento</strong>" was written by Javier Álvarez Liébana. It was last built on Última actualización: 20-12-2021.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
